from .server_request_handler import ServerRequestHandler
from .server_response_handler import ServerResponseHandler
from .server_routes_dispatcher import ServerRoutesDispatcher


expect_json = ServerRequestHandler.expect_json_content
get_json_content = ServerRequestHandler.get_json_content
get_request_id = ServerRequestHandler.get_request_id

return_exception = ServerResponseHandler.return_exception
return_json = ServerResponseHandler.return_json

http_delete = ServerRoutesDispatcher.expose_controller_http_delete_method
http_get = ServerRoutesDispatcher.expose_controller_http_get_method
http_put = ServerRoutesDispatcher.expose_controller_http_put_method
route = ServerRoutesDispatcher.expose_controller_class
